### ISSUE TITLE
"Create a service account" link broken

### ISSUE THREAD

**Issue by alexgleason** [tomdyson/wagalytics#21]
In the readme, this link is now broken: https://ga-dev-tools.appspot.com/embed-api/server-side-authorization

**Comment by tomdyson** [comment]
Weird. All the other pages in that section are still there:

https://ga-dev-tools.appspot.com/embed-api/

In the meantime, the source for the site is still available:

https://raw.githubusercontent.com/googleanalytics/ga-dev-tools/master/templates/embed-api/server-side-authorization.html

Do these instructions still work?

**Comment by tomdyson** [comment]
Relevant chunk of instructions scraped from the source of the disappeared page:

## Step 1: Create a service account and download the JSON key

Follow the steps in the Google Identity Platform documentation to [create a service account](https://developers.google.com/identity/protocols/OAuth2ServiceAccount#creatinganaccount) from the [Google Developer Console](https://console.developers.google.com/).

Once the service account is created, you can click the **Generate New JSON Key** button to create and download the key and add it to your project.

Important!  Make sure to store your JSON key file privately and securely. Do not check it in to a public repository or store it on a public server.

## Step 2: Add the service account as a user in Google Analytics

The service account you created in the previous step has an email address that you can add to any of the Google Analytics views you'd like to request data from. It's generally best to only grant the service account read-only access.

**Comment by alexgleason** [comment]
This works. Thanks for doing this updates so quickly!
