### ISSUE TITLE
Latest pypy version fail to install

### ISSUE THREAD

**Issue by Arussil** [tomdyson/wagalytics#41]
Hello,

tried to install latest Wagalytics today from pip and it fails if Wagtail is not already installed:

Step to reproduce:

pip install wagalytics

traceback:

>   Downloading https://files.pythonhosted.org/packages/33/8b/d12687ea4fc8a0057bcffa5f0932cc2d0c844d921bf4e5d0efec5fc39236/wagalytics-1.1.tar.gz (122kB)
    100% |████████████████████████████████| 122kB 4.8MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-unxhd3uf/wagalytics/setup.py", line 4, in <module>
        from wagtail.utils.setup import sdist
    ModuleNotFoundError: No module named 'wagtail'

version 1.0 works without problems

**Comment by alexgleason** [comment]
That's strange. Maybe has something to do with setup.py.
If you're installing Wagalytics you'll need Wagtail, which you can install first with `pip install wagtail`. Usually they are both included together in a requirements.txt.

**Comment by Arussil** [comment]
But install trough Pip works with version 1.0:

pip install "wagalytics<1.1"

does work as it resolves dependencies and install Wagtail during the process.

The problem it's also present when i use pip-compile to create the requirements.txt, even if Wagtail is inside the source requirements.ini.

Inside a virtualenv with Wagtail already installed before Wagalytics all works again.

**Comment by Arussil** [comment]
Seems like commit 2e389b545f8780076885783c5e45321f19376738 it's about this issue, but didn't get in v1.1

**Comment by KalobTaulien** [comment]
@Arussil you're correct, that didn't quite make it into v1.1. I'll update the pypi package hopefully soon. The commit you linked to fixed it. You can link to the fixed commit in setup.py with 

```python
    install_requires=[
        '...',
        'wagalytics @ https://github.com/tomdyson/wagalytics/archive/2e389b545f8780076885783c5e45321f19376738.zip',
    ],
```

I wasn't able to figure out exactly _why_ it fails with setup.py. A require `pip install wagalytics` works but using setup.py fails, and from what I could tell it's because setup.py downloads everything and install it afterwards, and it ran into an order-of-operations issue. I'm not 100% certain on that.

**Comment by Arussil** [comment]
@KalobTaulien thanks for the answer, at the moment we're still pinning <1.1 since it's not really a problem, will keep an eye for next release!

**Comment by KalobTaulien** [comment]
@Arussil I just updated the pypi package to v1.2. That should work for you now.

**Comment by Arussil** [comment]
@KalobTaulien, works perfectly, thanks!
