### ISSUE TITLE
Getting request.site.hostname

### ISSUE THREAD

**Issue by benmayocode** [tomdyson/wagalytics#51]
I'm throwing an error when I try to get the host from `request.site.hostname ` in views.py.

I raised it on StackOverflow [https://stackoverflow.com/questions/62331479/attributeerror-wsgirequest-object-has-no-attribute-site-wagtail-wagalyti/62332010#62332010](url), and learnt that `request.site` is deprecated.

I got out of my depth with this a while back. My understanding from the SO question is I'd need the wagalytics library to be updated to use it without modification.

I'm using wagtail 2.9

Cheers!

**Comment by cspollar** [comment]
Wagtail 2.9 deprecates `wagtail.core.middleware.SiteMiddleware` which makes the current site object available in `request.site`. 

>References to request.site in your code should be removed; the recommended way of retrieving the current site is Site.find_for_request(request)
Source: [Wagtail 2.9 Docs](https://docs.wagtail.io/en/stable/releases/2.9.html#sitemiddleware-and-request-site-deprecated)

There are 3 references to `request.site` in [views.py](https://github.com/tomdyson/wagalytics/blob/master/wagalytics/views.py) that will need to be updated before the middleware can be removed.

**Comment by 32bitsret** [comment]
Tell me about this issue. Story of my life right now.
